/*
 * ServerSuite.java
 * JUnit based test
 *
 * Created on June 17, 2004, 4:19 PM
 */

package transport.server;

import junit.framework.*;

/**
 *
 * @author ola
 */
public class ServerSuite extends TestCase {

	public ServerSuite(java.lang.String testName) {
		super(testName);
	}

	/**
	 * suite method automatically generated by JUnit module
	 */
	public static Test suite() {
		TestSuite suite=new TestSuite("ServerSuite");
		suite.addTest(transport.server.ArtistFactoryTest.suite());
		suite.addTest(transport.server.CarFactoryTest.suite());
		suite.addTest(transport.server.ConnectionFactoryTest.suite());
		suite.addTest(transport.server.FunctionaryFactoryTest.suite());
		suite.addTest(transport.server.MobilePhoneFactoryTest.suite());
		suite.addTest(transport.server.PlaceFactoryTest.suite());
		suite.addTest(transport.server.RoleFactoryTest.suite());
		suite.addTest(transport.server.TransportDropoffFactoryTest.suite());
		suite.addTest(transport.server.TransportFactoryTest.suite());
		return suite;
	}

	// TODO add test methods here, they have to start with 'test' name.
	// for example:
	// public void testHello() {}

}
