/*
 * AddArtist.java
 *
 * Created on June 15, 2004, 12:33 AM
 */

package transport.client;

import transport.logic.Artist;
import transport.server.ArtistFactory;

/**
 *
 * @author  ola
 */
public class ArtistEditor extends javax.swing.JInternalFrame {
	private Artist artist;
	
	/** Creates new form AddArtist */
	public ArtistEditor(Artist artist) {
		this.artist=artist;
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void initComponents() {//GEN-BEGIN:initComponents
                infoPanel = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField11 = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jTextField10 = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jTextField9 = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox();
                jLabel4 = new javax.swing.JLabel();
                jTextField7 = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jComboBox2 = new javax.swing.JComboBox();
                jLabel7 = new javax.swing.JLabel();
                jComboBox3 = new javax.swing.JComboBox();
                jLabel8 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                performerField = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                crewField = new javax.swing.JTextField();
                labelGuests = new javax.swing.JLabel();
                guestsField = new javax.swing.JTextField();
                buttonPanel = new javax.swing.JPanel();
                buttonOK = new javax.swing.JButton();
                buttonCancel = new javax.swing.JButton();

                setClosable(true);
                setResizable(true);
                setTitle("Add an artist");
                infoPanel.setLayout(new java.awt.GridLayout(11, 2));

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel1.setText("Name");
                infoPanel.add(jLabel1);

                infoPanel.add(jTextField11);

                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel2.setText("Contact name");
                infoPanel.add(jLabel2);

                infoPanel.add(jTextField10);

                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel6.setText("Phone number");
                infoPanel.add(jLabel6);

                infoPanel.add(jTextField9);

                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel3.setText("Arrival");
                infoPanel.add(jLabel3);

                infoPanel.add(jComboBox1);

                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel4.setText("Arrival time");
                infoPanel.add(jLabel4);

                jTextField7.setEditable(false);
                infoPanel.add(jTextField7);

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel5.setText("Hotel");
                infoPanel.add(jLabel5);

                infoPanel.add(jComboBox2);

                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel7.setText("Departure");
                infoPanel.add(jLabel7);

                infoPanel.add(jComboBox3);

                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel8.setText("Departure time");
                infoPanel.add(jLabel8);

                jTextField4.setEditable(false);
                infoPanel.add(jTextField4);

                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel9.setText("Performers");
                infoPanel.add(jLabel9);

                performerField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                performerFieldActionPerformed(evt);
                        }
                });

                infoPanel.add(performerField);

                jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel10.setText("Crew");
                infoPanel.add(jLabel10);

                infoPanel.add(crewField);

                labelGuests.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelGuests.setText("Guests");
                infoPanel.add(labelGuests);

                guestsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                infoPanel.add(guestsField);

                getContentPane().add(infoPanel, java.awt.BorderLayout.CENTER);

                buttonOK.setText("OK");
                buttonOK.setMnemonic('O');
                buttonOK.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                buttonOKActionPerformed(evt);
                        }
                });

                buttonPanel.add(buttonOK);

                buttonCancel.setText("Cancel");
                buttonCancel.setMnemonic('C');
                buttonPanel.add(buttonCancel);

                getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

                pack();
        }//GEN-END:initComponents

	private void performerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performerFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_performerFieldActionPerformed

	private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_buttonOKActionPerformed
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton buttonCancel;
        private javax.swing.JButton buttonOK;
        private javax.swing.JPanel buttonPanel;
        private javax.swing.JTextField crewField;
        private javax.swing.JTextField guestsField;
        private javax.swing.JPanel infoPanel;
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JComboBox jComboBox2;
        private javax.swing.JComboBox jComboBox3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JTextField jTextField10;
        private javax.swing.JTextField jTextField11;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField9;
        private javax.swing.JLabel labelGuests;
        private javax.swing.JTextField performerField;
        // End of variables declaration//GEN-END:variables
	
}
