/*
 * AddCar.java
 *
 * Created on June 26, 2004, 3:25 PM
 */

package transport.client;

import transport.logic.*;
import transport.server.*;

/**
 *
 * @author  ola
 */
public class CarEditor extends javax.swing.JInternalFrame {
	private Car car;
	
	public CarEditor() {
		this(new Car());
	}
	
	/** Creates new form AddCar */
	public CarEditor(Car car) {
		this.car=car;
		jbInit();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void jbInit() {//GEN-BEGIN:jbInit
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                regNoText = new javax.swing.JFormattedTextField();
                jLabel2 = new javax.swing.JLabel();
                carTypeText = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                seatNoText = new javax.swing.JFormattedTextField();
                jLabel4 = new javax.swing.JLabel();
                miscInfoText = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                okButton = new javax.swing.JButton();
                cancelButton = new javax.swing.JButton();

                jPanel1.setLayout(new java.awt.GridLayout(4, 2));

                jLabel1.setText("Registration number");
                jPanel1.add(jLabel1);

                regNoText.setText("jFormattedTextField1");
                regNoText.setNextFocusableComponent(carTypeText);
                jPanel1.add(regNoText);

                jLabel2.setText("Car type");
                jPanel1.add(jLabel2);

                carTypeText.setText("jTextField2");
                carTypeText.setNextFocusableComponent(seatNoText);
                jPanel1.add(carTypeText);

                jLabel3.setText("Number of seats");
                jPanel1.add(jLabel3);

                seatNoText.setText("jFormattedTextField2");
                seatNoText.setNextFocusableComponent(miscInfoText);
                jPanel1.add(seatNoText);

                jLabel4.setText("Misc info");
                jPanel1.add(jLabel4);

                miscInfoText.setText("jTextField4");
                miscInfoText.setNextFocusableComponent(okButton);
                jPanel1.add(miscInfoText);

                getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

                okButton.setMnemonic('O');
                okButton.setText("OK");
                okButton.setNextFocusableComponent(carTypeText);
                okButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                okButtonActionPerformed(evt);
                        }
                });

                jPanel2.add(okButton);

                cancelButton.setMnemonic('C');
                cancelButton.setText("Cancel");
                cancelButton.setNextFocusableComponent(regNoText);
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                jPanel2.add(cancelButton);

                getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

                pack();
        }//GEN-END:jbInit

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		// TODO add your handling code here:
		
		car.setCarType(carTypeText.getText());
		car.setMiscInfo(miscInfoText.getText());
		car.setRegNo(regNoText.getText());
		car.setNumberOfSeats(Integer.parseInt(seatNoText.getText()));
		
		CarFactory cf=new CarFactory();
		if (car.getId()== -1) {
			cf.newCar(car);
		} else {
			cf.updateCar(car);
		}
		this.dispose();
	}//GEN-LAST:event_okButtonActionPerformed
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButton;
        private javax.swing.JTextField carTypeText;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField miscInfoText;
        private javax.swing.JButton okButton;
        private javax.swing.JFormattedTextField regNoText;
        private javax.swing.JFormattedTextField seatNoText;
        // End of variables declaration//GEN-END:variables
	
}
