/*
 * AddFunctionary.java
 *
 * Created on June 26, 2004, 3:25 PM
 */

package transport.client;

/**
 *
 * @author  ola
 */
public class FunctionaryEditor extends javax.swing.JInternalFrame {
	
	/** Creates new form AddFunctionary */
	public FunctionaryEditor() {
		jbInit();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void jbInit() {//GEN-BEGIN:jbInit
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();

                jPanel1.setLayout(new java.awt.GridLayout(4, 2));

                jLabel1.setText("Name");
                jPanel1.add(jLabel1);

                jTextField1.setText("jTextField1");
                jPanel1.add(jTextField1);

                jLabel2.setText("Role");
                jPanel1.add(jLabel2);

                jPanel1.add(jComboBox1);

                jLabel3.setText("Begins working");
                jPanel1.add(jLabel3);

                jLabel4.setText("Stops working");
                jPanel1.add(jLabel4);

                getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

                jButton1.setMnemonic('O');
                jButton1.setText("OK");
                jPanel2.add(jButton1);

                jButton2.setMnemonic('C');
                jButton2.setText("Cancel");
                jPanel2.add(jButton2);

                getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

                pack();
        }//GEN-END:jbInit
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTextField jTextField1;
        // End of variables declaration//GEN-END:variables
	
}
