/*
 * ItemChooser.java
 *
 * Created on June 29, 2004, 12:19 AM
 */

package transport.client;

import javax.swing.*;

import transport.logic.*;
import transport.server.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  ola
 */
public class ItemChooser extends javax.swing.JPanel {
	DefaultListModel listModel=new DefaultListModel();
	Object type;
	MultipleChooser mc;

	/** Creates new form ItemChooser */
	public ItemChooser(Object type, MultipleChooser mc) {
		jbInit();
		this.type=type;
		this.mc=mc;
		refresh();
	}

public void refresh() {
          listModel.removeAllElements();
		if (type instanceof Artist) {
			ArtistFactory af=new ArtistFactory();
			Artist[] a=af.getAllArtists();
			for (int i=0; i < a.length; i++) {
				listModel.addElement(a[i]);
			}
		} else if (type instanceof Car) {
			CarFactory af=new CarFactory();
			Car[] a=af.getAllCars();
			for (int i=0; i < a.length; i++) {
				listModel.addElement(a[i]);
			}
		} else if (type instanceof Functionary) {
			FunctionaryFactory af=new FunctionaryFactory();
			Functionary[] a=af.getAllFunctionaries();
			for (int i=0; i < a.length; i++) {
				listModel.addElement(a[i]);
			}
		} else if (type instanceof MobilePhone) {
			MobilePhoneFactory af=new MobilePhoneFactory();
			MobilePhone[] a=af.getAllMobilePhones();
			for (int i=0; i < a.length; i++) {
				listModel.addElement(a[i]);
			}
		} else if (type instanceof Place) {
			PlaceFactory pf=new PlaceFactory();
			Place[] p=pf.getAllPlaces();
			for (int i=0;i<p.length;i++) {
				listModel.addElement(p[i]);
			}
		} else {
			throw new NullPointerException(
				"Trying to ItemChoose something which doesn't exist!");
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void jbInit() { //GEN-BEGIN:jbInit
		itemList=new javax.swing.JList();
		buttonPanel=new javax.swing.JPanel();
		addButton=new javax.swing.JButton();
		cancelButton=new javax.swing.JButton();

		this.setLayout(borderLayout1);
		addButton.addActionListener(new ItemChooser_addButton_actionAdapter(this));
		cancelButton.addActionListener(new
									   ItemChooser_cancelButton_actionAdapter(this));
		itemList.setModel(listModel);
		add(buttonPanel, BorderLayout.SOUTH);

		addButton.setMnemonic('A');
		addButton.setText("Add");

		cancelButton.setMnemonic('C');
		cancelButton.setText("Cancel");
		buttonPanel.add(addButton);
		buttonPanel.add(cancelButton);
    this.add(jScrollPane1, BorderLayout.CENTER);
    jScrollPane1.getViewport().add(itemList, null);
	} //GEN-END:jbInit

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton addButton;
	private javax.swing.JPanel buttonPanel;
	private javax.swing.JList itemList;
	BorderLayout borderLayout1 = new BorderLayout();
  JScrollPane jScrollPane1 = new JScrollPane();

	void addButton_actionPerformed(ActionEvent e) {
		Object o[]=itemList.getSelectedValues();

		for (int i=0; i < o.length; i++) {
			mc.add(o[i]);
		}
		mc.closeChooser();
	}

	void cancelButton_actionPerformed(ActionEvent e) {
		mc.closeChooser();
	}

	// End of variables declaration//GEN-END:variables

}

class ItemChooser_addButton_actionAdapter implements java.awt.event.ActionListener {
  ItemChooser adaptee;

  ItemChooser_addButton_actionAdapter(ItemChooser adaptee) {
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    adaptee.addButton_actionPerformed(e);
  }
}

class ItemChooser_cancelButton_actionAdapter implements java.awt.event.ActionListener {
  ItemChooser adaptee;

  ItemChooser_cancelButton_actionAdapter(ItemChooser adaptee) {
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    adaptee.cancelButton_actionPerformed(e);
  }
}
