/*
 * MainFrame.java
 *
 * Created on June 12, 2004, 5:32 PM
 */

package transport.src.transport.client;

/**
 *
 * @author  ola
 */
public class MainFrame extends javax.swing.JFrame {
	
	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void initComponents() {//GEN-BEGIN:initComponents
                ToolBar = new javax.swing.JToolBar();
                jDesktopPane1 = new javax.swing.JDesktopPane();
                MenuBar = new javax.swing.JMenuBar();
                MenuFile = new javax.swing.JMenu();
                MenuExit = new javax.swing.JMenuItem();
                Edit = new javax.swing.JMenu();
                AddThingsMenu = new javax.swing.JMenu();
                AddFunctionary = new javax.swing.JMenuItem();
                AddArtist = new javax.swing.JMenuItem();
                AddCar = new javax.swing.JMenuItem();

                setName("MainFrame");
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                exitForm(evt);
                        }
                });

                getContentPane().add(ToolBar, java.awt.BorderLayout.NORTH);

                getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

                MenuFile.setMnemonic('F');
                MenuFile.setText("File");
                MenuFile.setToolTipText("File menu");
                MenuFile.setActionCommand("File");
                MenuExit.setMnemonic('E');
                MenuExit.setText("Exit");
                MenuFile.add(MenuExit);

                MenuBar.add(MenuFile);
                MenuFile.getAccessibleContext().setAccessibleName("File");

                Edit.setMnemonic('E');
                Edit.setText("Edit");
                MenuBar.add(Edit);

                AddThingsMenu.setMnemonic('A');
                AddThingsMenu.setText("Add");
                AddFunctionary.setMnemonic('F');
                AddFunctionary.setText("Add Functionary");
                AddThingsMenu.add(AddFunctionary);

                AddArtist.setMnemonic('r');
                AddArtist.setText("Add Artist");
                AddThingsMenu.add(AddArtist);

                AddCar.setMnemonic('C');
                AddCar.setText("Add Car");
                AddThingsMenu.add(AddCar);

                MenuBar.add(AddThingsMenu);

                setJMenuBar(MenuBar);

                pack();
        }//GEN-END:initComponents
	
	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit(0);
	}//GEN-LAST:event_exitForm
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		new MainFrame().show();
	}
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem AddArtist;
        private javax.swing.JMenuItem AddCar;
        private javax.swing.JMenuItem AddFunctionary;
        private javax.swing.JMenu AddThingsMenu;
        private javax.swing.JMenu Edit;
        private javax.swing.JMenuBar MenuBar;
        private javax.swing.JMenuItem MenuExit;
        private javax.swing.JMenu MenuFile;
        private javax.swing.JToolBar ToolBar;
        private javax.swing.JDesktopPane jDesktopPane1;
        // End of variables declaration//GEN-END:variables
	
}
