/*
 * MainFrame.java
 *
 * Created on June 12, 2004, 5:32 PM
 */

package transport.client;

/**
 *
 * @author  ola
 */
public class MainFrame extends javax.swing.JFrame {
	
	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		this.setSize(800,600);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void initComponents() {//GEN-BEGIN:initComponents
                desktopPane = new javax.swing.JDesktopPane();
                MenuBar = new javax.swing.JMenuBar();
                MenuFile = new javax.swing.JMenu();
                MenuExit = new javax.swing.JMenuItem();
                Edit = new javax.swing.JMenu();
                AddThingsMenu = new javax.swing.JMenu();
                FunctionaryItem = new javax.swing.JMenuItem();
                ArtistItem = new javax.swing.JMenuItem();
                CarItem = new javax.swing.JMenuItem();
                TransportItem = new javax.swing.JMenuItem();

                setTitle("Arvikafestivalen Booking System");
                setName("MainFrame");
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                exitForm(evt);
                        }
                });

                desktopPane.setAutoscrolls(true);
                getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

                MenuFile.setMnemonic('F');
                MenuFile.setText("File");
                MenuFile.setToolTipText("File menu");
                MenuExit.setMnemonic('E');
                MenuExit.setText("Exit");
                MenuExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                menuExitHandler(evt);
                        }
                });

                MenuFile.add(MenuExit);

                MenuBar.add(MenuFile);

                Edit.setMnemonic('E');
                Edit.setText("Edit");
                MenuBar.add(Edit);

                AddThingsMenu.setText("Add");
                AddThingsMenu.setMnemonic('A');
                FunctionaryItem.setText("Add Functionary");
                FunctionaryItem.setMnemonic('F');
                AddThingsMenu.add(FunctionaryItem);

                ArtistItem.setText("Add Artist");
                ArtistItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ArtistItemActionPerformed(evt);
                        }
                });
                ArtistItem.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                displayArtistFrame(evt);
                        }
                });

                AddThingsMenu.add(ArtistItem);

                CarItem.setText("Add Car");
                CarItem.setMnemonic('C');
                AddThingsMenu.add(CarItem);

                TransportItem.setText("Add Transport");
                TransportItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
                AddThingsMenu.add(TransportItem);

                MenuBar.add(AddThingsMenu);

                setJMenuBar(MenuBar);

                pack();
        }//GEN-END:initComponents

	private void menuExitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitHandler
		// TODO add your handling code here:
		System.exit(0);
	}//GEN-LAST:event_menuExitHandler

	private void ArtistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistItemActionPerformed
		// TODO add your handling code here:
		desktopPane.add(new ArtistFrame());
	}//GEN-LAST:event_ArtistItemActionPerformed

	private void displayArtistFrame(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayArtistFrame
		//desktopPane.add(new ArtistFrame());
	}//GEN-LAST:event_displayArtistFrame
	
	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit(0);
	}//GEN-LAST:event_exitForm
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		new MainFrame().show();
	}
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu AddThingsMenu;
        private javax.swing.JMenuItem ArtistItem;
        private javax.swing.JMenuItem CarItem;
        private javax.swing.JMenu Edit;
        private javax.swing.JMenuItem FunctionaryItem;
        private javax.swing.JMenuBar MenuBar;
        private javax.swing.JMenuItem MenuExit;
        private javax.swing.JMenu MenuFile;
        private javax.swing.JMenuItem TransportItem;
        private javax.swing.JDesktopPane desktopPane;
        // End of variables declaration//GEN-END:variables
	
}
