/*
 * MobilePhoneEditor.java
 *
 * Created on June 29, 2004, 11:00 PM
 */

package transport.client;

import transport.logic.*;
import javax.swing.*;
import java.awt.event.*;
import transport.server.MobilePhoneFactory;
import java.awt.Image;
import java.io.File;

/**
 *
 * @author  ola
 */
public class MobilePhoneEditor extends GenericEditor {
//public class MobilePhoneEditor extends javax.swing.JInternalFrame {
	MobilePhone mobilePhone;
	public MobilePhoneEditor() {
		this(new MobilePhone());
                jbInit();
	}

	/** Creates new form MobilePhoneEditor */
	public MobilePhoneEditor(MobilePhone mobilePhone) {
		jbInit();
		edit(mobilePhone);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void jbInit() { //GEN-BEGIN:jbInit
          ImageIcon frameIcon = new ImageIcon(this.getClass().getResource(
              "../pics/miniAF.png"));
          this.setFrameIcon(frameIcon);
    this.setResizable(true);
		jPanel1=new javax.swing.JPanel();
		jLabel1=new javax.swing.JLabel();
		jPanel2=new javax.swing.JPanel();
		okButton=new javax.swing.JButton();
		cancelButton=new javax.swing.JButton();

		setTitle("Mobile Phone Editor");
		jPanel1.setLayout(new java.awt.GridLayout());

		jLabel1.setText("Number");
    mobilePhoneText.setText("");
    okButton.addActionListener(new MobilePhoneEditor_okButton_actionAdapter(this));
    cancelButton.addActionListener(new MobilePhoneEditor_cancelButton_actionAdapter(this));
    jPanel1.add(jLabel1);
    jPanel1.add(mobilePhoneText, null);


		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		okButton.setText("OK");
		jPanel2.add(okButton);

		cancelButton.setText("Cancel");
		jPanel2.add(cancelButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);
		getRootPane().setDefaultButton(okButton);

		pack();
	} //GEN-END:jbInit

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton okButton;
  JTextField mobilePhoneText = new JTextField();

	/**
	 * edit
	 *
	 * @param o Object
	 */
	public void edit(Object o) {
		this.mobilePhone=(MobilePhone)o;

		if (mobilePhone.getId() == -1) {
			this.setTitle("Add a mobile phone");
			okButton.setText("New");
			okButton.setMnemonic('N');
		} else {
			this.setTitle("Update a mobile phone");
			okButton.setText("Update");
			okButton.setMnemonic('U');

			mobilePhoneText.setText(mobilePhone.getNumber());
		}
	}

	/**
	 * editNew
	 */
	public void editNew() {
		edit(new MobilePhone());
	}

	void okButton_actionPerformed(ActionEvent e) {
		mobilePhone.setNumber(mobilePhoneText.getText());

		MobilePhoneFactory mpf=new MobilePhoneFactory();
		MainFrame mf=(MainFrame)this.getTopLevelAncestor();

		if (mobilePhone.getId() == -1) {
			mpf.newMobilePhone(mobilePhone);
			mf.refreshLists(mobilePhone, transport.client.tablemodel.GenericTableModel.REFRESH_INSERT);
		} else {
			mpf.updateMobilePhone(mobilePhone);
			mf.refreshLists(mobilePhone, transport.client.tablemodel.GenericTableModel.REFRESH_UPDATE);
		}

		this.dispose();
	}

	void cancelButton_actionPerformed(ActionEvent e) {
		this.dispose();
	}


	// End of variables declaration//GEN-END:variables

}

class MobilePhoneEditor_okButton_actionAdapter implements java.awt.event.ActionListener {
  MobilePhoneEditor adaptee;

  MobilePhoneEditor_okButton_actionAdapter(MobilePhoneEditor adaptee) {
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    adaptee.okButton_actionPerformed(e);
  }
}

class MobilePhoneEditor_cancelButton_actionAdapter implements java.awt.event.ActionListener {
  MobilePhoneEditor adaptee;

  MobilePhoneEditor_cancelButton_actionAdapter(MobilePhoneEditor adaptee) {
    this.adaptee = adaptee;
  }
  public void actionPerformed(ActionEvent e) {
    adaptee.cancelButton_actionPerformed(e);
  }
}
