/*
 * PickDateTimeCombo.java
 *
 * Created on June 26, 2004, 4:31 PM
 */

package transport.client;

import javax.swing.*;

/**
 *
 * @author  ola
 */
public class PickDateTimeCombo extends javax.swing.JPanel {

	/** Creates new form PickDateTimeCombo */
	public PickDateTimeCombo() {
		jbInit();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
        private void jbInit() {//GEN-BEGIN:jbInit
                launchPickDateTime = new javax.swing.JButton();
                dateField = new javax.swing.JFormattedTextField();

                setLayout(new java.awt.BorderLayout());

                launchPickDateTime.setText("...");
                launchPickDateTime.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                launchPickDateTimeActionPerformed(evt);
                        }
                });

                add(launchPickDateTime, java.awt.BorderLayout.EAST);

                dateField.setEditable(false);
                dateField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
                add(dateField, java.awt.BorderLayout.CENTER);

        }//GEN-END:jbInit

	private void launchPickDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchPickDateTimeActionPerformed
		// TODO add your handling code here:
		//new PickDateTime(dateSpinner.get);
	}//GEN-LAST:event_launchPickDateTimeActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFormattedTextField dateField;
        private javax.swing.JButton launchPickDateTime;
        // End of variables declaration//GEN-END:variables

}
