/*
 * Role.java
 *
 * Created on June 12, 2004, 6:05 PM
 */

package transport.client;

/**
 *
 * @author  ola
 */
public class RoleFrame extends javax.swing.JInternalFrame {
	
	/** Creates new form Role */
	public RoleFrame() {
		jbInit();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void jbInit() {//GEN-BEGIN:jbInit
		
		pack();
	}//GEN-END:jbInit
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
	
}
