/*
 * AddTransport.java
 *
 * Created on June 26, 2004, 3:25 PM
 */

package transport.client;

import transport.logic.*;

/**
 *
 * @author  ola
 */
public class TransportEditor extends GenericEditor {
	Transport transport;

	public TransportEditor() {
		this(new Transport());
	}

	/** Creates new form AddTransport */
	public TransportEditor(Transport transport) {
		jbInit();
		edit(transport);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void jbInit() { //GEN-BEGIN:jbInit
		jPanel2=new javax.swing.JPanel();
		okButton=new javax.swing.JButton();
		cancelButton=new javax.swing.JButton();
		jPanel3=new javax.swing.JPanel();
		jPanel1=new javax.swing.JPanel();
		jLabel1=new javax.swing.JLabel();
		jLabel2=new javax.swing.JLabel();
		jLabel3=new javax.swing.JLabel();
		jLabel4=new javax.swing.JLabel();
		jLabel5=new javax.swing.JLabel();
		jLabel6=new javax.swing.JLabel();
		jLabel7=new javax.swing.JLabel();
		jLabel8=new javax.swing.JLabel();
		jLabel9=new javax.swing.JLabel();
		jLabel10=new javax.swing.JLabel();
		jLabel11=new javax.swing.JLabel();

		okButton.setMnemonic('O');
		okButton.setText("OK");
		jPanel2.add(okButton);

		cancelButton.setMnemonic('C');
		cancelButton.setText("Cancel");
		jPanel2.add(cancelButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		jPanel3.setLayout(new java.awt.BorderLayout());

		jPanel1.setLayout(new java.awt.GridLayout(11, 1));

		jLabel1.setText("Artists");
		jPanel1.add(jLabel1);

		jLabel2.setText("Cars");
		jPanel1.add(jLabel2);

		jLabel3.setText("Functionaries");
		jPanel1.add(jLabel3);

		jLabel4.setText("Internal");
		jPanel1.add(jLabel4);

		jLabel5.setText("Dropoffs");
		jPanel1.add(jLabel5);

		jLabel6.setText("Mobile phones");
		jPanel1.add(jLabel6);

		jLabel7.setText("Start time");
		jPanel1.add(jLabel7);

		jLabel8.setText("Distance");
		jPanel1.add(jLabel8);

		jLabel9.setText("Return time");
		jPanel1.add(jLabel9);

		jLabel10.setText("Actual return time");
		jPanel1.add(jLabel10);

		jLabel11.setText("Misc info");
		jPanel1.add(jLabel11);

		jPanel3.add(jPanel1, java.awt.BorderLayout.WEST);

		getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

		pack();
	} //GEN-END:jbInit

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JButton okButton;

	/**
	 * edit
	 *
	 * @param o Object
	 */
	public void edit(Object o) {
		/*if (artist.getId() == -1) {
		 this.setTitle("Add an artist");
		 okButton.setText("New");
		 okButton.setMnemonic('N');
		 } else {
		 this.setTitle("Update an artist");
		 okButton.setText("Update");
		 okButton.setMnemonic('U');
		 nameText.setText(artist.getName());
		 contactNameText.setText(artist.getContactName());
		 phoneNumberText.setText(artist.getTelephoneNo());
		 }*/

	}

	/**
	 * editNew
	 */
	public void editNew() {
		edit(null);
	}

	// End of variables declaration//GEN-END:variables

}
