/*
 * TransportDropoff.java
 *
 * Created on June 12, 2004, 6:07 PM
 */

package transport.client;

/**
 *
 * @author  ola
 */
public class TransportDropoffFrame extends javax.swing.JInternalFrame {

	/** Creates new form TransportDropoff */
	public TransportDropoffFrame() {
		jbInit();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void jbInit() { //GEN-BEGIN:jbInit

		pack();
	} //GEN-END:jbInit

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
